; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes='simplify-cfg<switch-to-lookup>' < %s | FileCheck %s
; Using a Zig driver https://gist.github.com/shawnl/8137f62f7dbcfd539f6cf1925387cd38
;after-patch, covered lookup table: 509.8MiB/sec
;lookup table, not covered, only valid digits to prime the branch predictor: 437.8MiB/sec
;lookup table, not covered, random bytes: 242.0MiB/sec
;before-patch, no lookup table: 205.4MiB/sec

; ModuleID = 'chartodigit.c'
source_filename = "chartodigit.c"
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

; Function Attrs: norecurse nounwind readnone uwtable
define dso_local zeroext i8 @char_to_digit(i8 zeroext) local_unnamed_addr #0 {
; CHECK-LABEL: @char_to_digit(
; CHECK-NEXT:    [[TMP2:%.*]] = sub i8 [[TMP0:%.*]], 48
; CHECK-NEXT:    switch i8 [[TMP2]], label [[TMP18:%.*]] [
; CHECK-NEXT:    i8 0, label [[TMP19:%.*]]
; CHECK-NEXT:    i8 1, label [[TMP3:%.*]]
; CHECK-NEXT:    i8 2, label [[TMP4:%.*]]
; CHECK-NEXT:    i8 3, label [[TMP5:%.*]]
; CHECK-NEXT:    i8 4, label [[TMP6:%.*]]
; CHECK-NEXT:    i8 5, label [[TMP7:%.*]]
; CHECK-NEXT:    i8 6, label [[TMP8:%.*]]
; CHECK-NEXT:    i8 7, label [[TMP9:%.*]]
; CHECK-NEXT:    i8 8, label [[TMP10:%.*]]
; CHECK-NEXT:    i8 9, label [[TMP11:%.*]]
; CHECK-NEXT:    i8 49, label [[TMP12:%.*]]
; CHECK-NEXT:    i8 50, label [[TMP13:%.*]]
; CHECK-NEXT:    i8 51, label [[TMP14:%.*]]
; CHECK-NEXT:    i8 52, label [[TMP15:%.*]]
; CHECK-NEXT:    i8 53, label [[TMP16:%.*]]
; CHECK-NEXT:    i8 54, label [[TMP17:%.*]]
; CHECK-NEXT:    ]
; CHECK:       3:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       4:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       5:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       6:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       7:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       8:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       9:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       10:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       11:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       12:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       13:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       14:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       15:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       16:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       17:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       18:
; CHECK-NEXT:    br label [[TMP19]]
; CHECK:       19:
; CHECK-NEXT:    [[TMP20:%.*]] = phi i8 [ -1, [[TMP18]] ], [ 15, [[TMP17]] ], [ 14, [[TMP16]] ], [ 13, [[TMP15]] ], [ 12, [[TMP14]] ], [ 11, [[TMP13]] ], [ 10, [[TMP12]] ], [ 9, [[TMP11]] ], [ 8, [[TMP10]] ], [ 7, [[TMP9]] ], [ 6, [[TMP8]] ], [ 5, [[TMP7]] ], [ 4, [[TMP6]] ], [ 3, [[TMP5]] ], [ 2, [[TMP4]] ], [ 1, [[TMP3]] ], [ 0, [[TMP1:%.*]] ]
; CHECK-NEXT:    ret i8 [[TMP20]]
;
  switch i8 %0, label %17 [
  i8 48, label %18
  i8 49, label %2
  i8 50, label %3
  i8 51, label %4
  i8 52, label %5
  i8 53, label %6
  i8 54, label %7
  i8 55, label %8
  i8 56, label %9
  i8 57, label %10
  i8 97, label %11
  i8 98, label %12
  i8 99, label %13
  i8 100, label %14
  i8 101, label %15
  i8 102, label %16
  ]

; <label>:2:                                      ; preds = %1
  br label %18

; <label>:3:                                      ; preds = %1
  br label %18

; <label>:4:                                      ; preds = %1
  br label %18

; <label>:5:                                      ; preds = %1
  br label %18

; <label>:6:                                      ; preds = %1
  br label %18

; <label>:7:                                      ; preds = %1
  br label %18

; <label>:8:                                      ; preds = %1
  br label %18

; <label>:9:                                      ; preds = %1
  br label %18

; <label>:10:                                     ; preds = %1
  br label %18

; <label>:11:                                     ; preds = %1
  br label %18

; <label>:12:                                     ; preds = %1
  br label %18

; <label>:13:                                     ; preds = %1
  br label %18

; <label>:14:                                     ; preds = %1
  br label %18

; <label>:15:                                     ; preds = %1
  br label %18

; <label>:16:                                     ; preds = %1
  br label %18

; <label>:17:                                     ; preds = %1
  br label %18

; <label>:18:                                     ; preds = %1, %17, %16, %15, %14, %13, %12, %11, %10, %9, %8, %7, %6, %5, %4, %3, %2
  %19 = phi i8 [ -1, %17 ], [ 15, %16 ], [ 14, %15 ], [ 13, %14 ], [ 12, %13 ], [ 11, %12 ], [ 10, %11 ], [ 9, %10 ], [ 8, %9 ], [ 7, %8 ], [ 6, %7 ], [ 5, %6 ], [ 4, %5 ], [ 3, %4 ], [ 2, %3 ], [ 1, %2 ], [ 0, %1 ]
  ret i8 %19
}

attributes #0 = { norecurse nounwind readnone uwtable "correctly-rounded-divide-sqrt-fp-math"="false" "disable-tail-calls"="false" "less-precise-fpmad"="false" "min-legal-vector-width"="0" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-jump-tables"="false" "no-nans-fp-math"="false" "no-signed-zeros-fp-math"="false" "no-trapping-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+fxsr,+mmx,+sse,+sse2,+x87" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{!"clang version 8.0.0-3 (tags/RELEASE_800/final)"}
